baseURL = "https://blog.sanket0x.com/"
languageCode = "en-us"
title = "Sanket Bijawe"
theme = "PaperMod"

enableRobotsTXT = true
disableKinds = ["RSS"]

[params]
description = "Engineering blog about backend systems, distributed systems and experiments."
fuseOpts = { isCaseSensitive = false, shouldSort = true }

# UI
defaultTheme = "auto"

# Post metadata
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowCodeCopyButtons = true

# Table of contents
ShowToc = true
TocOpen = false

# Homepage content
mainSections = ["posts"]

[params.label]
text = "Sanket Bijawe"
url = "/"

[markup]
  [markup.highlight]
    style = "github"
    lineNos = true

[permalinks]
posts = "/:slug/"

[outputs]
home = ["HTML", "JSON"]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 10

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 20